<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",78,106);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",170,199);
$z[2][4]['name']="typename";
$z[3]=Array("field","",227,258);
$z[3][4]['name']="typenameen";
$z[4]=Array("channel","\r\n              <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n              ",343,513);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>