<?php
$z[0]=Array("global","",103,135);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n        <li class=\"{dede:field.currentstyle/}\">\r\n          <div class=\"navf\"><a href=\"{dede:field name='typeurl'/}\" title=\"\"> <span class=\"navcurbg\"></span> <span class=\"navcur\">{dede:field name='typename'/}</span> <span class=\"navon\">{dede:field name='typenameen'/}</span> </a></div>\r\n          <div class=\"nav-son\">\r\n            <ul>\r\n              {dede:channel type='son' noself='yes' }\r\n              <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n              {/dede:channel}\r\n            </ul>\r\n          </div>\r\n        </li>\r\n        ",430,1100);
$z[1][4]['typeid']="top";
$z[1][4]['row']="9";
$z[1][4]['currentstyle']="hover";
$z[2]=Array("global","",1165,1197);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1364,1396);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1562,1594);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1787,1819);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1984,2016);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",2163,2195);
$z[7][4]['name']="cfg_templets_skin";

?>